//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Accessor : GltfChildOfRootProperty {
        
        /// <summary>
        /// Backing field for BufferView.
        /// </summary>
        private System.Nullable<int> m_bufferView;
        
        /// <summary>
        /// Backing field for ByteOffset.
        /// </summary>
        private int m_byteOffset = 0;
        
        /// <summary>
        /// Backing field for ComponentType.
        /// </summary>
        private ComponentTypeEnum m_componentType;
        
        /// <summary>
        /// Backing field for Normalized.
        /// </summary>
        private bool m_normalized = false;
        
        /// <summary>
        /// Backing field for Count.
        /// </summary>
        private int m_count;
        
        /// <summary>
        /// Backing field for Type.
        /// </summary>
        private TypeEnum m_type;
        
        /// <summary>
        /// Backing field for Max.
        /// </summary>
        private float[] m_max;
        
        /// <summary>
        /// Backing field for Min.
        /// </summary>
        private float[] m_min;
        
        /// <summary>
        /// Backing field for Sparse.
        /// </summary>
        private AccessorSparse m_sparse;
        
        /// <summary>
        /// The index of the bufferView.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("bufferView")]
        public System.Nullable<int> BufferView {
            get {
                return this.m_bufferView;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("BufferView", value, "Expected value to be greater than or equal to 0");
                }
                this.m_bufferView = value;
            }
        }
        
        /// <summary>
        /// The offset relative to the start of the buffer view in bytes.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("byteOffset")]
        public int ByteOffset {
            get {
                return this.m_byteOffset;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("ByteOffset", value, "Expected value to be greater than or equal to 0");
                }
                this.m_byteOffset = value;
            }
        }
        
        /// <summary>
        /// The datatype of the accessor's components.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("componentType")]
        public ComponentTypeEnum ComponentType {
            get {
                return this.m_componentType;
            }
            set {
                this.m_componentType = value;
            }
        }
        
        /// <summary>
        /// Specifies whether integer data values are normalized before usage.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("normalized")]
        public bool Normalized {
            get {
                return this.m_normalized;
            }
            set {
                this.m_normalized = value;
            }
        }
        
        /// <summary>
        /// The number of elements referenced by this accessor.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("count")]
        public int Count {
            get {
                return this.m_count;
            }
            set {
                if ((value < 1)) {
                    throw new System.ArgumentOutOfRangeException("Count", value, "Expected value to be greater than or equal to 1");
                }
                this.m_count = value;
            }
        }
        
        /// <summary>
        /// Specifies if the accessor's elements are scalars, vectors, or matrices.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public TypeEnum Type {
            get {
                return this.m_type;
            }
            set {
                this.m_type = value;
            }
        }
        
        /// <summary>
        /// Maximum value of each component in this accessor.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("max")]
        public float[] Max {
            get {
                return this.m_max;
            }
            set {
                if ((value == null)) {
                    this.m_max = value;
                    return;
                }
                if ((value.Length < 1u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 16u)) {
                    throw new System.ArgumentException("Array too long");
                }
                this.m_max = value;
            }
        }
        
        /// <summary>
        /// Minimum value of each component in this accessor.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("min")]
        public float[] Min {
            get {
                return this.m_min;
            }
            set {
                if ((value == null)) {
                    this.m_min = value;
                    return;
                }
                if ((value.Length < 1u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 16u)) {
                    throw new System.ArgumentException("Array too long");
                }
                this.m_min = value;
            }
        }
        
        /// <summary>
        /// Sparse storage of elements that deviate from their initialization value.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sparse")]
        public AccessorSparse Sparse {
            get {
                return this.m_sparse;
            }
            set {
                this.m_sparse = value;
            }
        }
        
        public bool ShouldSerializeBufferView() {
            return ((m_bufferView == null) 
                        == false);
        }
        
        public bool ShouldSerializeByteOffset() {
            return ((m_byteOffset == 0) 
                        == false);
        }
        
        public bool ShouldSerializeNormalized() {
            return ((m_normalized == false) 
                        == false);
        }
        
        public bool ShouldSerializeMax() {
            return ((m_max == null) 
                        == false);
        }
        
        public bool ShouldSerializeMin() {
            return ((m_min == null) 
                        == false);
        }
        
        public bool ShouldSerializeSparse() {
            return ((m_sparse == null) 
                        == false);
        }
        
        public enum ComponentTypeEnum {
            
            BYTE = 5120,
            
            UNSIGNED_BYTE = 5121,
            
            SHORT = 5122,
            
            UNSIGNED_SHORT = 5123,
            
            UNSIGNED_INT = 5125,
            
            FLOAT = 5126,
        }
        
        [System.Text.Json.Serialization.JsonConverter(typeof(TypeEnumConverter))]
        public struct TypeEnum : System.IEquatable<TypeEnum> {
            
private readonly string m_value;

public TypeEnum(string value) {
    this.m_value = value;
}

public static readonly TypeEnum SCALAR = new TypeEnum("SCALAR");
public static readonly TypeEnum VEC2 = new TypeEnum("VEC2");
public static readonly TypeEnum VEC3 = new TypeEnum("VEC3");
public static readonly TypeEnum VEC4 = new TypeEnum("VEC4");
public static readonly TypeEnum MAT2 = new TypeEnum("MAT2");
public static readonly TypeEnum MAT3 = new TypeEnum("MAT3");
public static readonly TypeEnum MAT4 = new TypeEnum("MAT4");

public string Value {
    get { return this.m_value; }
}

public override string ToString() {
    return this.m_value;
}

public bool Equals(TypeEnum other) {
    return string.Equals(this.m_value, other.m_value, System.StringComparison.Ordinal);
}

public override bool Equals(object obj) {
    return ((obj is TypeEnum) && this.Equals(((TypeEnum)(obj))));
}

public override int GetHashCode() {
    return ((this.m_value == null) ? 0 : this.m_value.GetHashCode());
}

public static bool operator ==(TypeEnum left, TypeEnum right) {
    return left.Equals(right);
}

public static bool operator !=(TypeEnum left, TypeEnum right) {
    return (left.Equals(right) == false);
}

public static implicit operator string(TypeEnum value) {
    return value.m_value;
}

public static implicit operator TypeEnum(string value) {
    return new TypeEnum(value);
}

public class TypeEnumConverter : System.Text.Json.Serialization.JsonConverter<TypeEnum> {
    public override TypeEnum Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
        if (reader.TokenType != System.Text.Json.JsonTokenType.String) {
            throw new System.Text.Json.JsonException("Expected a string value for TypeEnum.");
        }
        return new TypeEnum(reader.GetString());
    }
    public override void Write(System.Text.Json.Utf8JsonWriter writer, TypeEnum value, System.Text.Json.JsonSerializerOptions options) {
        writer.WriteStringValue(value.m_value);
    }
}

        }
    }
}
