//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class AccessorSparse : GltfProperty {
        
        /// <summary>
        /// Backing field for Count.
        /// </summary>
        private int m_count;
        
        /// <summary>
        /// Backing field for Indices.
        /// </summary>
        private AccessorSparseIndices m_indices;
        
        /// <summary>
        /// Backing field for Values.
        /// </summary>
        private AccessorSparseValues m_values;
        
        /// <summary>
        /// Number of deviating accessor values stored in the sparse array.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("count")]
        public int Count {
            get {
                return this.m_count;
            }
            set {
                if ((value < 1)) {
                    throw new System.ArgumentOutOfRangeException("Count", value, "Expected value to be greater than or equal to 1");
                }
                this.m_count = value;
            }
        }
        
        /// <summary>
        /// An object pointing to a buffer view containing the indices of deviating accessor values. The number of indices is equal to `count`. Indices **MUST** strictly increase.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("indices")]
        public AccessorSparseIndices Indices {
            get {
                return this.m_indices;
            }
            set {
                this.m_indices = value;
            }
        }
        
        /// <summary>
        /// An object pointing to a buffer view containing the deviating accessor values.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("values")]
        public AccessorSparseValues Values {
            get {
                return this.m_values;
            }
            set {
                this.m_values = value;
            }
        }
        
        public bool ShouldSerializeIndices() {
            return ((m_indices == null) 
                        == false);
        }
        
        public bool ShouldSerializeValues() {
            return ((m_values == null) 
                        == false);
        }
    }
}
