//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class AnimationSampler : GltfProperty {
        
        /// <summary>
        /// Backing field for Input.
        /// </summary>
        private int m_input;
        
        /// <summary>
        /// Backing field for Interpolation.
        /// </summary>
        private InterpolationEnum m_interpolation = InterpolationEnum.LINEAR;
        
        /// <summary>
        /// Backing field for Output.
        /// </summary>
        private int m_output;
        
        /// <summary>
        /// The index of an accessor containing keyframe timestamps.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("input")]
        public int Input {
            get {
                return this.m_input;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Input", value, "Expected value to be greater than or equal to 0");
                }
                this.m_input = value;
            }
        }
        
        /// <summary>
        /// Interpolation algorithm.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("interpolation")]
        public InterpolationEnum Interpolation {
            get {
                return this.m_interpolation;
            }
            set {
                this.m_interpolation = value;
            }
        }
        
        /// <summary>
        /// The index of an accessor, containing keyframe output values.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("output")]
        public int Output {
            get {
                return this.m_output;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Output", value, "Expected value to be greater than or equal to 0");
                }
                this.m_output = value;
            }
        }
        
        public bool ShouldSerializeInterpolation() {
            return ((m_interpolation == InterpolationEnum.LINEAR) 
                        == false);
        }
        
        [System.Text.Json.Serialization.JsonConverter(typeof(InterpolationEnumConverter))]
        public struct InterpolationEnum : System.IEquatable<InterpolationEnum> {
            
private readonly string m_value;

public InterpolationEnum(string value) {
    this.m_value = value;
}

public static readonly InterpolationEnum LINEAR = new InterpolationEnum("LINEAR");
public static readonly InterpolationEnum STEP = new InterpolationEnum("STEP");
public static readonly InterpolationEnum CUBICSPLINE = new InterpolationEnum("CUBICSPLINE");

public string Value {
    get { return this.m_value; }
}

public override string ToString() {
    return this.m_value;
}

public bool Equals(InterpolationEnum other) {
    return string.Equals(this.m_value, other.m_value, System.StringComparison.Ordinal);
}

public override bool Equals(object obj) {
    return ((obj is InterpolationEnum) && this.Equals(((InterpolationEnum)(obj))));
}

public override int GetHashCode() {
    return ((this.m_value == null) ? 0 : this.m_value.GetHashCode());
}

public static bool operator ==(InterpolationEnum left, InterpolationEnum right) {
    return left.Equals(right);
}

public static bool operator !=(InterpolationEnum left, InterpolationEnum right) {
    return (left.Equals(right) == false);
}

public static implicit operator string(InterpolationEnum value) {
    return value.m_value;
}

public static implicit operator InterpolationEnum(string value) {
    return new InterpolationEnum(value);
}

public class InterpolationEnumConverter : System.Text.Json.Serialization.JsonConverter<InterpolationEnum> {
    public override InterpolationEnum Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
        if (reader.TokenType != System.Text.Json.JsonTokenType.String) {
            throw new System.Text.Json.JsonException("Expected a string value for InterpolationEnum.");
        }
        return new InterpolationEnum(reader.GetString());
    }
    public override void Write(System.Text.Json.Utf8JsonWriter writer, InterpolationEnum value, System.Text.Json.JsonSerializerOptions options) {
        writer.WriteStringValue(value.m_value);
    }
}

        }
    }
}
