//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class AnimationChannelTarget : GltfProperty {
        
        /// <summary>
        /// Backing field for Node.
        /// </summary>
        private System.Nullable<int> m_node;
        
        /// <summary>
        /// Backing field for Path.
        /// </summary>
        private PathEnum m_path;
        
        /// <summary>
        /// The index of the node to animate. When undefined, the animated object **MAY** be defined by an extension.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("node")]
        public System.Nullable<int> Node {
            get {
                return this.m_node;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Node", value, "Expected value to be greater than or equal to 0");
                }
                this.m_node = value;
            }
        }
        
        /// <summary>
        /// The name of the node's TRS property to animate, or the `"weights"` of the Morph Targets it instantiates. For the `"translation"` property, the values that are provided by the sampler are the translation along the X, Y, and Z axes. For the `"rotation"` property, the values are a quaternion in the order (x, y, z, w), where w is the scalar. For the `"scale"` property, the values are the scaling factors along the X, Y, and Z axes.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("path")]
        public PathEnum Path {
            get {
                return this.m_path;
            }
            set {
                this.m_path = value;
            }
        }
        
        public bool ShouldSerializeNode() {
            return ((m_node == null) 
                        == false);
        }
        
        [System.Text.Json.Serialization.JsonConverter(typeof(PathEnumConverter))]
        public struct PathEnum : System.IEquatable<PathEnum> {
            
private readonly string m_value;

public PathEnum(string value) {
    this.m_value = value;
}

public static readonly PathEnum translation = new PathEnum("translation");
public static readonly PathEnum rotation = new PathEnum("rotation");
public static readonly PathEnum scale = new PathEnum("scale");
public static readonly PathEnum weights = new PathEnum("weights");

public string Value {
    get { return this.m_value; }
}

public override string ToString() {
    return this.m_value;
}

public bool Equals(PathEnum other) {
    return string.Equals(this.m_value, other.m_value, System.StringComparison.Ordinal);
}

public override bool Equals(object obj) {
    return ((obj is PathEnum) && this.Equals(((PathEnum)(obj))));
}

public override int GetHashCode() {
    return ((this.m_value == null) ? 0 : this.m_value.GetHashCode());
}

public static bool operator ==(PathEnum left, PathEnum right) {
    return left.Equals(right);
}

public static bool operator !=(PathEnum left, PathEnum right) {
    return (left.Equals(right) == false);
}

public static implicit operator string(PathEnum value) {
    return value.m_value;
}

public static implicit operator PathEnum(string value) {
    return new PathEnum(value);
}

public class PathEnumConverter : System.Text.Json.Serialization.JsonConverter<PathEnum> {
    public override PathEnum Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
        if (reader.TokenType != System.Text.Json.JsonTokenType.String) {
            throw new System.Text.Json.JsonException("Expected a string value for PathEnum.");
        }
        return new PathEnum(reader.GetString());
    }
    public override void Write(System.Text.Json.Utf8JsonWriter writer, PathEnum value, System.Text.Json.JsonSerializerOptions options) {
        writer.WriteStringValue(value.m_value);
    }
}

        }
    }
}
