//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Asset : GltfProperty {
        
        /// <summary>
        /// Backing field for Copyright.
        /// </summary>
        private string m_copyright;
        
        /// <summary>
        /// Backing field for Generator.
        /// </summary>
        private string m_generator;
        
        /// <summary>
        /// Backing field for Version.
        /// </summary>
        private string m_version;
        
        /// <summary>
        /// Backing field for MinVersion.
        /// </summary>
        private string m_minVersion;
        
        /// <summary>
        /// A copyright message suitable for display to credit the content creator.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("copyright")]
        public string Copyright {
            get {
                return this.m_copyright;
            }
            set {
                this.m_copyright = value;
            }
        }
        
        /// <summary>
        /// Tool that generated this glTF model.  Useful for debugging.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("generator")]
        public string Generator {
            get {
                return this.m_generator;
            }
            set {
                this.m_generator = value;
            }
        }
        
        /// <summary>
        /// The glTF version in the form of `<major>.<minor>` that this asset targets.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public string Version {
            get {
                return this.m_version;
            }
            set {
                this.m_version = value;
            }
        }
        
        /// <summary>
        /// The minimum glTF version in the form of `<major>.<minor>` that this asset targets. This property **MUST NOT** be greater than the asset version.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("minVersion")]
        public string MinVersion {
            get {
                return this.m_minVersion;
            }
            set {
                this.m_minVersion = value;
            }
        }
        
        public bool ShouldSerializeCopyright() {
            return ((m_copyright == null) 
                        == false);
        }
        
        public bool ShouldSerializeGenerator() {
            return ((m_generator == null) 
                        == false);
        }
        
        public bool ShouldSerializeVersion() {
            return ((m_version == null) 
                        == false);
        }
        
        public bool ShouldSerializeMinVersion() {
            return ((m_minVersion == null) 
                        == false);
        }
    }
}
