//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Buffer : GltfChildOfRootProperty {
        
        /// <summary>
        /// Backing field for Uri.
        /// </summary>
        private string m_uri;
        
        /// <summary>
        /// Backing field for ByteLength.
        /// </summary>
        private int m_byteLength;
        
        /// <summary>
        /// The URI (or IRI) of the buffer.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("uri")]
        public string Uri {
            get {
                return this.m_uri;
            }
            set {
                this.m_uri = value;
            }
        }
        
        /// <summary>
        /// The length of the buffer in bytes.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("byteLength")]
        public int ByteLength {
            get {
                return this.m_byteLength;
            }
            set {
                if ((value < 1)) {
                    throw new System.ArgumentOutOfRangeException("ByteLength", value, "Expected value to be greater than or equal to 1");
                }
                this.m_byteLength = value;
            }
        }
        
        public bool ShouldSerializeUri() {
            return ((m_uri == null) 
                        == false);
        }
    }
}
