//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class CameraOrthographic : GltfProperty {
        
        /// <summary>
        /// Backing field for Xmag.
        /// </summary>
        private float m_xmag;
        
        /// <summary>
        /// Backing field for Ymag.
        /// </summary>
        private float m_ymag;
        
        /// <summary>
        /// Backing field for Zfar.
        /// </summary>
        private float m_zfar;
        
        /// <summary>
        /// Backing field for Znear.
        /// </summary>
        private float m_znear;
        
        /// <summary>
        /// The floating-point horizontal magnification of the view. This value **MUST NOT** be equal to zero. This value **SHOULD NOT** be negative.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("xmag")]
        public float Xmag {
            get {
                return this.m_xmag;
            }
            set {
                this.m_xmag = value;
            }
        }
        
        /// <summary>
        /// The floating-point vertical magnification of the view. This value **MUST NOT** be equal to zero. This value **SHOULD NOT** be negative.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("ymag")]
        public float Ymag {
            get {
                return this.m_ymag;
            }
            set {
                this.m_ymag = value;
            }
        }
        
        /// <summary>
        /// The floating-point distance to the far clipping plane. This value **MUST NOT** be equal to zero. `zfar` **MUST** be greater than `znear`.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("zfar")]
        public float Zfar {
            get {
                return this.m_zfar;
            }
            set {
                if ((value <= 0D)) {
                    throw new System.ArgumentOutOfRangeException("Zfar", value, "Expected value to be greater than 0");
                }
                this.m_zfar = value;
            }
        }
        
        /// <summary>
        /// The floating-point distance to the near clipping plane.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("znear")]
        public float Znear {
            get {
                return this.m_znear;
            }
            set {
                if ((value < 0D)) {
                    throw new System.ArgumentOutOfRangeException("Znear", value, "Expected value to be greater than or equal to 0");
                }
                this.m_znear = value;
            }
        }
    }
}
