//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class CameraPerspective : GltfProperty {
        
        /// <summary>
        /// Backing field for AspectRatio.
        /// </summary>
        private System.Nullable<float> m_aspectRatio;
        
        /// <summary>
        /// Backing field for Yfov.
        /// </summary>
        private float m_yfov;
        
        /// <summary>
        /// Backing field for Zfar.
        /// </summary>
        private System.Nullable<float> m_zfar;
        
        /// <summary>
        /// Backing field for Znear.
        /// </summary>
        private float m_znear;
        
        /// <summary>
        /// The floating-point aspect ratio of the field of view.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("aspectRatio")]
        public System.Nullable<float> AspectRatio {
            get {
                return this.m_aspectRatio;
            }
            set {
                if ((value <= 0D)) {
                    throw new System.ArgumentOutOfRangeException("AspectRatio", value, "Expected value to be greater than 0");
                }
                this.m_aspectRatio = value;
            }
        }
        
        /// <summary>
        /// The floating-point vertical field of view in radians. This value **SHOULD** be less than π.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("yfov")]
        public float Yfov {
            get {
                return this.m_yfov;
            }
            set {
                if ((value <= 0D)) {
                    throw new System.ArgumentOutOfRangeException("Yfov", value, "Expected value to be greater than 0");
                }
                this.m_yfov = value;
            }
        }
        
        /// <summary>
        /// The floating-point distance to the far clipping plane.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("zfar")]
        public System.Nullable<float> Zfar {
            get {
                return this.m_zfar;
            }
            set {
                if ((value <= 0D)) {
                    throw new System.ArgumentOutOfRangeException("Zfar", value, "Expected value to be greater than 0");
                }
                this.m_zfar = value;
            }
        }
        
        /// <summary>
        /// The floating-point distance to the near clipping plane.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("znear")]
        public float Znear {
            get {
                return this.m_znear;
            }
            set {
                if ((value <= 0D)) {
                    throw new System.ArgumentOutOfRangeException("Znear", value, "Expected value to be greater than 0");
                }
                this.m_znear = value;
            }
        }
        
        public bool ShouldSerializeAspectRatio() {
            return ((m_aspectRatio == null) 
                        == false);
        }
        
        public bool ShouldSerializeZfar() {
            return ((m_zfar == null) 
                        == false);
        }
    }
}
