//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Camera : GltfChildOfRootProperty {
        
        /// <summary>
        /// Backing field for Orthographic.
        /// </summary>
        private CameraOrthographic m_orthographic;
        
        /// <summary>
        /// Backing field for Perspective.
        /// </summary>
        private CameraPerspective m_perspective;
        
        /// <summary>
        /// Backing field for Type.
        /// </summary>
        private TypeEnum m_type;
        
        /// <summary>
        /// An orthographic camera containing properties to create an orthographic projection matrix. This property **MUST NOT** be defined when `perspective` is defined.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("orthographic")]
        public CameraOrthographic Orthographic {
            get {
                return this.m_orthographic;
            }
            set {
                this.m_orthographic = value;
            }
        }
        
        /// <summary>
        /// A perspective camera containing properties to create a perspective projection matrix. This property **MUST NOT** be defined when `orthographic` is defined.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("perspective")]
        public CameraPerspective Perspective {
            get {
                return this.m_perspective;
            }
            set {
                this.m_perspective = value;
            }
        }
        
        /// <summary>
        /// Specifies if the camera uses a perspective or orthographic projection.
        /// </summary>
        [System.Text.Json.Serialization.JsonConverter(typeof(JsonStringEnumConverterWithEnumMemberAttrSupport<TypeEnum>))]
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public TypeEnum Type {
            get {
                return this.m_type;
            }
            set {
                this.m_type = value;
            }
        }
        
        public bool ShouldSerializeOrthographic() {
            return ((m_orthographic == null) 
                        == false);
        }
        
        public bool ShouldSerializePerspective() {
            return ((m_perspective == null) 
                        == false);
        }
        
        public enum TypeEnum {
            
            perspective,
            
            orthographic,
        }
    }
}
