//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Camera : GltfChildOfRootProperty {
        
        /// <summary>
        /// Backing field for Orthographic.
        /// </summary>
        private CameraOrthographic m_orthographic;
        
        /// <summary>
        /// Backing field for Perspective.
        /// </summary>
        private CameraPerspective m_perspective;
        
        /// <summary>
        /// Backing field for Type.
        /// </summary>
        private TypeEnum m_type;
        
        /// <summary>
        /// An orthographic camera containing properties to create an orthographic projection matrix. This property **MUST NOT** be defined when `perspective` is defined.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("orthographic")]
        public CameraOrthographic Orthographic {
            get {
                return this.m_orthographic;
            }
            set {
                this.m_orthographic = value;
            }
        }
        
        /// <summary>
        /// A perspective camera containing properties to create a perspective projection matrix. This property **MUST NOT** be defined when `orthographic` is defined.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("perspective")]
        public CameraPerspective Perspective {
            get {
                return this.m_perspective;
            }
            set {
                this.m_perspective = value;
            }
        }
        
        /// <summary>
        /// Specifies if the camera uses a perspective or orthographic projection.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public TypeEnum Type {
            get {
                return this.m_type;
            }
            set {
                this.m_type = value;
            }
        }
        
        public bool ShouldSerializeOrthographic() {
            return ((m_orthographic == null) 
                        == false);
        }
        
        public bool ShouldSerializePerspective() {
            return ((m_perspective == null) 
                        == false);
        }
        
        [System.Text.Json.Serialization.JsonConverter(typeof(TypeEnumConverter))]
        public struct TypeEnum : System.IEquatable<TypeEnum> {
            
private readonly string m_value;

public TypeEnum(string value) {
    this.m_value = value;
}

public static readonly TypeEnum perspective = new TypeEnum("perspective");
public static readonly TypeEnum orthographic = new TypeEnum("orthographic");

public string Value {
    get { return this.m_value; }
}

public override string ToString() {
    return this.m_value;
}

public bool Equals(TypeEnum other) {
    return string.Equals(this.m_value, other.m_value, System.StringComparison.Ordinal);
}

public override bool Equals(object obj) {
    return ((obj is TypeEnum) && this.Equals(((TypeEnum)(obj))));
}

public override int GetHashCode() {
    return ((this.m_value == null) ? 0 : this.m_value.GetHashCode());
}

public static bool operator ==(TypeEnum left, TypeEnum right) {
    return left.Equals(right);
}

public static bool operator !=(TypeEnum left, TypeEnum right) {
    return (left.Equals(right) == false);
}

public static implicit operator string(TypeEnum value) {
    return value.m_value;
}

public static implicit operator TypeEnum(string value) {
    return new TypeEnum(value);
}

public class TypeEnumConverter : System.Text.Json.Serialization.JsonConverter<TypeEnum> {
    public override TypeEnum Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
        if (reader.TokenType != System.Text.Json.JsonTokenType.String) {
            throw new System.Text.Json.JsonException("Expected a string value for TypeEnum.");
        }
        return new TypeEnum(reader.GetString());
    }
    public override void Write(System.Text.Json.Utf8JsonWriter writer, TypeEnum value, System.Text.Json.JsonSerializerOptions options) {
        writer.WriteStringValue(value.m_value);
    }
}

        }
    }
}
