//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Image : GltfChildOfRootProperty {
        
        /// <summary>
        /// Backing field for Uri.
        /// </summary>
        private string m_uri;
        
        /// <summary>
        /// Backing field for MimeType.
        /// </summary>
        private System.Nullable<MimeTypeEnum> m_mimeType;
        
        /// <summary>
        /// Backing field for BufferView.
        /// </summary>
        private System.Nullable<int> m_bufferView;
        
        /// <summary>
        /// The URI (or IRI) of the image.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("uri")]
        public string Uri {
            get {
                return this.m_uri;
            }
            set {
                this.m_uri = value;
            }
        }
        
        /// <summary>
        /// The image's media type. This field **MUST** be defined when `bufferView` is defined.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("mimeType")]
        public System.Nullable<MimeTypeEnum> MimeType {
            get {
                return this.m_mimeType;
            }
            set {
                this.m_mimeType = value;
            }
        }
        
        /// <summary>
        /// The index of the bufferView that contains the image. This field **MUST NOT** be defined when `uri` is defined.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("bufferView")]
        public System.Nullable<int> BufferView {
            get {
                return this.m_bufferView;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("BufferView", value, "Expected value to be greater than or equal to 0");
                }
                this.m_bufferView = value;
            }
        }
        
        public bool ShouldSerializeUri() {
            return ((m_uri == null) 
                        == false);
        }
        
        public bool ShouldSerializeMimeType() {
            return ((m_mimeType == null) 
                        == false);
        }
        
        public bool ShouldSerializeBufferView() {
            return ((m_bufferView == null) 
                        == false);
        }
        
        [System.Text.Json.Serialization.JsonConverter(typeof(MimeTypeEnumConverter))]
        public struct MimeTypeEnum : System.IEquatable<MimeTypeEnum> {
            
private readonly string m_value;

public MimeTypeEnum(string value) {
    this.m_value = value;
}

public static readonly MimeTypeEnum image_jpeg = new MimeTypeEnum("image/jpeg");
public static readonly MimeTypeEnum image_png = new MimeTypeEnum("image/png");

public string Value {
    get { return this.m_value; }
}

public override string ToString() {
    return this.m_value;
}

public bool Equals(MimeTypeEnum other) {
    return string.Equals(this.m_value, other.m_value, System.StringComparison.Ordinal);
}

public override bool Equals(object obj) {
    return ((obj is MimeTypeEnum) && this.Equals(((MimeTypeEnum)(obj))));
}

public override int GetHashCode() {
    return ((this.m_value == null) ? 0 : this.m_value.GetHashCode());
}

public static bool operator ==(MimeTypeEnum left, MimeTypeEnum right) {
    return left.Equals(right);
}

public static bool operator !=(MimeTypeEnum left, MimeTypeEnum right) {
    return (left.Equals(right) == false);
}

public static implicit operator string(MimeTypeEnum value) {
    return value.m_value;
}

public static implicit operator MimeTypeEnum(string value) {
    return new MimeTypeEnum(value);
}

public class MimeTypeEnumConverter : System.Text.Json.Serialization.JsonConverter<MimeTypeEnum> {
    public override MimeTypeEnum Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
        if (reader.TokenType != System.Text.Json.JsonTokenType.String) {
            throw new System.Text.Json.JsonException("Expected a string value for MimeTypeEnum.");
        }
        return new MimeTypeEnum(reader.GetString());
    }
    public override void Write(System.Text.Json.Utf8JsonWriter writer, MimeTypeEnum value, System.Text.Json.JsonSerializerOptions options) {
        writer.WriteStringValue(value.m_value);
    }
}

        }
    }
}
