//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class MaterialPbrMetallicRoughness : GltfProperty {
        
        /// <summary>
        /// Backing field for BaseColorFactor.
        /// </summary>
        private float[] m_baseColorFactor = new float[] {
                1F,
                1F,
                1F,
                1F};
        
        /// <summary>
        /// Backing field for BaseColorTexture.
        /// </summary>
        private TextureInfo m_baseColorTexture;
        
        /// <summary>
        /// Backing field for MetallicFactor.
        /// </summary>
        private float m_metallicFactor = 1F;
        
        /// <summary>
        /// Backing field for RoughnessFactor.
        /// </summary>
        private float m_roughnessFactor = 1F;
        
        /// <summary>
        /// Backing field for MetallicRoughnessTexture.
        /// </summary>
        private TextureInfo m_metallicRoughnessTexture;
        
        /// <summary>
        /// The factors for the base color of the material.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("baseColorFactor")]
        public float[] BaseColorFactor {
            get {
                return this.m_baseColorFactor;
            }
            set {
                if ((value.Length < 4u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 4u)) {
                    throw new System.ArgumentException("Array too long");
                }
                int index = 0;
                for (index = 0; (index < value.Length); index = (index + 1)) {
                    if ((value[index] < 0D)) {
                        throw new System.ArgumentOutOfRangeException();
                    }
                }
                for (index = 0; (index < value.Length); index = (index + 1)) {
                    if ((value[index] > 1D)) {
                        throw new System.ArgumentOutOfRangeException();
                    }
                }
                this.m_baseColorFactor = value;
            }
        }
        
        /// <summary>
        /// The base color texture.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("baseColorTexture")]
        public TextureInfo BaseColorTexture {
            get {
                return this.m_baseColorTexture;
            }
            set {
                this.m_baseColorTexture = value;
            }
        }
        
        /// <summary>
        /// The factor for the metalness of the material.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("metallicFactor")]
        public float MetallicFactor {
            get {
                return this.m_metallicFactor;
            }
            set {
                if ((value < 0D)) {
                    throw new System.ArgumentOutOfRangeException("MetallicFactor", value, "Expected value to be greater than or equal to 0");
                }
                if ((value > 1D)) {
                    throw new System.ArgumentOutOfRangeException("MetallicFactor", value, "Expected value to be less than or equal to 1");
                }
                this.m_metallicFactor = value;
            }
        }
        
        /// <summary>
        /// The factor for the roughness of the material.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("roughnessFactor")]
        public float RoughnessFactor {
            get {
                return this.m_roughnessFactor;
            }
            set {
                if ((value < 0D)) {
                    throw new System.ArgumentOutOfRangeException("RoughnessFactor", value, "Expected value to be greater than or equal to 0");
                }
                if ((value > 1D)) {
                    throw new System.ArgumentOutOfRangeException("RoughnessFactor", value, "Expected value to be less than or equal to 1");
                }
                this.m_roughnessFactor = value;
            }
        }
        
        /// <summary>
        /// The metallic-roughness texture.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("metallicRoughnessTexture")]
        public TextureInfo MetallicRoughnessTexture {
            get {
                return this.m_metallicRoughnessTexture;
            }
            set {
                this.m_metallicRoughnessTexture = value;
            }
        }
        
        public bool ShouldSerializeBaseColorFactor() {
            return (m_baseColorFactor.SequenceEqual(new float[] {
                        1F,
                        1F,
                        1F,
                        1F}) == false);
        }
        
        public bool ShouldSerializeBaseColorTexture() {
            return ((m_baseColorTexture == null) 
                        == false);
        }
        
        public bool ShouldSerializeMetallicFactor() {
            return ((m_metallicFactor == 1F) 
                        == false);
        }
        
        public bool ShouldSerializeRoughnessFactor() {
            return ((m_roughnessFactor == 1F) 
                        == false);
        }
        
        public bool ShouldSerializeMetallicRoughnessTexture() {
            return ((m_metallicRoughnessTexture == null) 
                        == false);
        }
    }
}
