//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class MaterialOcclusionTextureInfo : TextureInfo {
        
        /// <summary>
        /// Backing field for Strength.
        /// </summary>
        private float m_strength = 1F;
        
        /// <summary>
        /// A scalar multiplier controlling the amount of occlusion applied.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("strength")]
        public float Strength {
            get {
                return this.m_strength;
            }
            set {
                if ((value < 0D)) {
                    throw new System.ArgumentOutOfRangeException("Strength", value, "Expected value to be greater than or equal to 0");
                }
                if ((value > 1D)) {
                    throw new System.ArgumentOutOfRangeException("Strength", value, "Expected value to be less than or equal to 1");
                }
                this.m_strength = value;
            }
        }
        
        public bool ShouldSerializeStrength() {
            return ((m_strength == 1F) 
                        == false);
        }
    }
}
