//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class MaterialNormalTextureInfo : TextureInfo {
        
        /// <summary>
        /// Backing field for Scale.
        /// </summary>
        private float m_scale = 1F;
        
        /// <summary>
        /// The scalar parameter applied to each normal vector of the normal texture.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("scale")]
        public float Scale {
            get {
                return this.m_scale;
            }
            set {
                this.m_scale = value;
            }
        }
        
        public bool ShouldSerializeScale() {
            return ((m_scale == 1F) 
                        == false);
        }
    }
}
