//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Mesh : GltfChildOfRootProperty {
        
        /// <summary>
        /// Backing field for Primitives.
        /// </summary>
        private MeshPrimitive[] m_primitives;
        
        /// <summary>
        /// Backing field for Weights.
        /// </summary>
        private float[] m_weights;
        
        /// <summary>
        /// An array of primitives, each defining geometry to be rendered.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("primitives")]
        public MeshPrimitive[] Primitives {
            get {
                return this.m_primitives;
            }
            set {
                if ((value == null)) {
                    this.m_primitives = value;
                    return;
                }
                if ((value.Length < 1u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                this.m_primitives = value;
            }
        }
        
        /// <summary>
        /// Array of weights to be applied to the morph targets. The number of array elements **MUST** match the number of morph targets.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("weights")]
        public float[] Weights {
            get {
                return this.m_weights;
            }
            set {
                if ((value == null)) {
                    this.m_weights = value;
                    return;
                }
                if ((value.Length < 1u)) {
                    throw new System.ArgumentException("Array not long enough");
                }
                this.m_weights = value;
            }
        }
        
        public bool ShouldSerializePrimitives() {
            return ((m_primitives == null) 
                        == false);
        }
        
        public bool ShouldSerializeWeights() {
            return ((m_weights == null) 
                        == false);
        }
    }
}
