//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class TextureInfo : GltfProperty {
        
        /// <summary>
        /// Backing field for Index.
        /// </summary>
        private int m_index;
        
        /// <summary>
        /// Backing field for TexCoord.
        /// </summary>
        private int m_texCoord = 0;
        
        /// <summary>
        /// The index of the texture.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequired()]
        [System.Text.Json.Serialization.JsonPropertyName("index")]
        public int Index {
            get {
                return this.m_index;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Index", value, "Expected value to be greater than or equal to 0");
                }
                this.m_index = value;
            }
        }
        
        /// <summary>
        /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("texCoord")]
        public int TexCoord {
            get {
                return this.m_texCoord;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("TexCoord", value, "Expected value to be greater than or equal to 0");
                }
                this.m_texCoord = value;
            }
        }
        
        public bool ShouldSerializeTexCoord() {
            return ((m_texCoord == 0) 
                        == false);
        }
    }
}
