//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema {
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Texture : GltfChildOfRootProperty {
        
        /// <summary>
        /// Backing field for Sampler.
        /// </summary>
        private System.Nullable<int> m_sampler;
        
        /// <summary>
        /// Backing field for Source.
        /// </summary>
        private System.Nullable<int> m_source;
        
        /// <summary>
        /// The index of the sampler used by this texture. When undefined, a sampler with repeat wrapping and auto filtering **SHOULD** be used.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sampler")]
        public System.Nullable<int> Sampler {
            get {
                return this.m_sampler;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Sampler", value, "Expected value to be greater than or equal to 0");
                }
                this.m_sampler = value;
            }
        }
        
        /// <summary>
        /// The index of the image used by this texture. When undefined, an extension or other mechanism **SHOULD** supply an alternate texture source, otherwise behavior is undefined.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("source")]
        public System.Nullable<int> Source {
            get {
                return this.m_source;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Source", value, "Expected value to be greater than or equal to 0");
                }
                this.m_source = value;
            }
        }
        
        public bool ShouldSerializeSampler() {
            return ((m_sampler == null) 
                        == false);
        }
        
        public bool ShouldSerializeSource() {
            return ((m_source == null) 
                        == false);
        }
    }
}
