//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader {
    using glTFLoader.Schema;
    
    
    // base gltf context. always serializes values, default or not
    [System.Text.Json.Serialization.JsonSerializable(typeof(Gltf))]
    [System.Text.Json.Serialization.JsonSerializable(typeof(System.Text.Json.JsonElement))]
    [System.Text.Json.Serialization.JsonSerializable(typeof(Accessor.ComponentTypeEnum), TypeInfoPropertyName="Accessor_ComponentTypeEnum")]
    [System.Text.Json.Serialization.JsonSerializable(typeof(AccessorSparseIndices.ComponentTypeEnum), TypeInfoPropertyName="AccessorSparseIndices_ComponentTypeEnum")]
    [System.Text.Json.Serialization.JsonSerializable(typeof(Accessor.TypeEnum), TypeInfoPropertyName="Accessor_TypeEnum")]
    [System.Text.Json.Serialization.JsonSerializable(typeof(Camera.TypeEnum), TypeInfoPropertyName="Camera_TypeEnum")]
    [System.Text.Json.Serialization.JsonSourceGenerationOptions()]
    public partial class BaseGltfJsonContext : System.Text.Json.Serialization.JsonSerializerContext {
    }
}
